# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Center for Quantum Simulation
email: hujiazhong01@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  We are a new center at Tsinghua’s department of physics – the Quantum Simulation Center. We are working on quantum simulations using ultracold atomic platforms, led by Professors Cheng Chin, Wenlan Chen, and Jiazhong Hu. We come from the University of Chicago and Massachusetts Institute of Technology.
baseurl: "/quantumsimulation"
url: ""

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


theme: jekyll-theme-minimal